In [1]:
#----------------------------------------------------------------------------
# Vector Spaces
# Chapter 1 in the QUANTUM COMPUTING AND QUANTUM MACHINE lEARNING BOOK
#----------------------------------------------------------------------------
# Version 1.0
# (c) 2025 Jesse Van Griensven, Roydon Fraser, and Jose Rosas 
# Licence:  MIT - Citation required
#----------------------------------------------------------------------------
# Qiskit changes frequently. 
# We recommend using the latest version from the book code repository at:
# https://github.com/pedroer/quantum-computing-for-engineers/blob/main/requirements.txt
import numpy as np
import sympy as sp
#-------------------------------------------------------------
def sprint(Matrix):
    """ Prints a numpy Matrix in a nice format with sympy """
    # The input Matrix can be a Numpy or a Sympy Matrix
    SMatrix = sp.Matrix(Matrix)
    display( SMatrix )
    return

#-------------------------------------------------------------
# Check if a vector is a linear combination of v1, v2, v3
def is_linear_combination(target, basis_vectors):
    # Solve the system Ax = b, where A = basis_vectors, b = target
    A = np.column_stack(basis_vectors)
    b = target
    try:
        solution = np.linalg.solve(A, b)
        print("The target vector is a linear combination.")
        print("Solution (coefficients):", solution)
    except np.linalg.LinAlgError:
        print("The target vector is NOT a linear combination.")
        
    return
#-------------------------------------------------------------

# Define vectors in R^3
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
v3 = np.array([0, 0, 1])

# Target vector
target_vector = np.array([1, 2, 3])
basis_vectors = [v1, v2, v3]

# Print Inputs
print("vectors in R^3")
print("v1: \n", v1)
print("v2: \n", v2)
print("v3: \n", v3)
print()
print("Target Vector: \n", target_vector)
print()
print("Basis Vector:")
sprint(basis_vectors)
print()


# Check if a vector is a linear combination of v1, v2, v3
is_linear_combination(target_vector, basis_vectors)

# Span demonstration: create a span of vectors
span_vectors = [v1, v2]
linear_combination = 2 * v1 + 3 * v2
print("Linear Combination of v1 and v2:", linear_combination)


vectors in R^3
v1: 
 [1 0 0]
v2: 
 [0 1 0]
v3: 
 [0 0 1]

Target Vector: 
 [1 2 3]

Basis Vector:


Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])


The target vector is a linear combination.
Solution (coefficients): [1. 2. 3.]
Linear Combination of v1 and v2: [2 3 0]
